[package]
name = "rigs-macro"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "Rigs procedural macro"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", features = ["proc-macro"] }
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
